allowBuilds:
  '@clerk/shared': set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - "@clerk/shared"
  - unrs-resolver
  - "@next/swc-darwin-arm64"
  - sharp
verifyDepsBeforeRun: false
